config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"
urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"
urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github_login"),
    path("login/github/callback/", views.github_callback, name="github_callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete_verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
]

templates/partials/footer.html
<footer class="container max-w-full text-center py-10 border-t text-gray-800 font-medium">
  &copy; 2020 Airbnbn clone gogo
</footer>

templates/partials/messages.html
{% if  messages %}
<ul class="absolute right-0 left-0 top-0 flex justify-center">
    {% for message in messages %}
    <li class="message font-medium bg-gray-700 rounded-full z-10 w-64 text-center text-white py-4 px-6 {% if message.tags %} {{ message.tags }} {% endif %}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center font-sm font-medium h-full">
  {% if user.is_authenticated %}
    {% if request.session.is_hosting%}
    <li class="nav_link"><a href="{% url 'users:switch-hosting'%}">Guest Mode</a></li>
    <li class="nav_link"><a href="{% url 'rooms:create'%}">Upload</a></li>

    {% else %}
    <li class="nav_link"><a href="{% url 'users:switch-hosting'%}">Host Mode</a></li>
    {% endif %}
    <li class="nav_link"><a href="{{user.get_absolute_url}}">Profile</a></li>
    <li class="nav_link"><a href="{% url "users:logout"%}">Logout</a></li>
  {% else %}
    <li class="nav_link"><a href="{% url "users:login"%}">Login</a></li>
    <li class="nav_link"><a href="{% url "users:signup"%}">Signup</a></li>
  {% endif %}
</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href={% url "users:github_login" %} class="btn mb-1 border border-gray-500">
       <i class="fab fa-github-alt"></i> Continue with Github
    </a>
    <a class="btn mb-1 border border-gray-500 py-5">
       <i class="fas fa-comment"></i> Continue with Kakao
    </a>
</div>
<div class="w-full flex items-center">
   <div class="h-px w-full bg-gray-400"></div>
      <span class="text-gray-600 font-medium mx-4 text-sm">or</span>
   <div class="h-px w-full bg-gray-400"></div>
 </div>