config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"
urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"
urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
]

templates/mixins/room_card.html
<div class="w-1/4 mb-10 px-3 overflow-hidden">
    <a href="{% url "rooms:detail" room.pk%}">
        <div class="w-full h-64 bg-cover bg-center rounded-lg" style="background-image: url({{room.first_photo}});"></div>

        <div class="flex justify-between mb-2">
            <div class="w-4/5 truncate">
            {% if room.host.superhost %}
            <span class="uppercase font-medium text-black text-sm py-px px-1 border border-black rounded">superhost</span>
            {% endif %}
                {{room.city}} {{room.country.name}}
            </div>
            <div>
                <span><i class="fas fa-star text-red-500"></i>{{room.total_rating}}</span>
            </div>
        </div>
        <span class="w-11/12 block text-black truncate">{{room.name}}</span>
    </a>
</div>

templates/mixins/user_avatar.html
{% if user.avatar %}
    <div class="{{h_and_w|default:'h-20 w-20'}}rounded-full bg-center bg-cover" style="background-image: url({{user_obj.avatar.url}});">                
    </div>
{% else %}
    <div class="{{h_and_w|default:'h-20 w-20'}} rounded-full bg-gray-700 text-white flex justify-center items-center">
        <span class="{{text|default:'text-3xl'}}">{{user.first_name|first}}</span>
    </div>
{% endif %}