config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"
urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"
urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models
from users import models as user_models
from cal import Calendar


class AbstractItem(core_models.TimeStampedModel):
    """Abstract Item"""

    name = models.CharField(max_length=140)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    """ RoomType Object Definition"""

    class Meta:
        verbose_name = "Room Type"


class Amenity(AbstractItem):
    """ Amenity Object Definition"""

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):
    """ Facility Object Definition"""

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):
    """ HouseRule Object Definition"""

    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.TimeStampedModel):

    """ Photo Object Definiton """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):

    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    adress = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        user_models.User, related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        RoomType, related_name="rooms", on_delete=models.SET_NULL, null=True
    )

    amenities = models.ManyToManyField(Amenity, related_name="rooms", blank=True)
    facilities = models.ManyToManyField(Facility, related_name="rooms", blank=True)
    house_rules = models.ManyToManyField(HouseRule, related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews))
        return 0

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        four_photos = self.photos.all()[1:5]
        return four_photos

    def get_calendars(self):
        current_calendar = Calendar(2019, 11)
        next_calendar = Calendar(2019, 12)
        return (current_calendar, next_calendar)

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        empty_label="Any kind", queryset=models.RoomType.objects.all(), required=False
    )

    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)

    amenities = forms.ModelMultipleChoiceField(
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    facilities = forms.ModelMultipleChoiceField(
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )


class AddPhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "adress",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):

        room = super().save(commit=False)
        return room

rooms/views.py
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.http import Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django_countries import countries
from . import models, forms
from users import mixins as user_mixins

# Create your views here.


class HomeView(ListView):

    """ Home View Defintion """

    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "price"
    context_object_name = "rooms"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


# def room_detail(request, pk):
#     try:
#         room = models.Room.objects.get(pk=pk)
#         return render(request, "rooms/detail.html", {"room": room})
#     except models.Room.DoesNotExist:
#         raise Http404()
class RoomDetail(DetailView):
    """ RoomDetail Definition"""

    model = models.Room


class SearchView(View):
    """ SearchView Definition """

    def get(self, request):
        country = request.GET.get("country")
        if country:
            form = forms.SearchForm(request.GET)
            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                bedrooms = form.cleaned_data.get("bedrooms")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}
                if city != "Anywhere":
                    filter_args["city__startswith"] = city
                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price
                if beds is not None:
                    filter_args["beds__gte"] = beds
                if guests is not None:
                    filter_args["guests__gte"] = guests
                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms
                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True
                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity
                for facility in facilities:
                    filter_args["facilities"] = facility
                qs = models.Room.objects.filter(**filter_args).order_by("-created")

                paginator = Paginator(qs, 1, orphans=0)
                num_pages = paginator.num_pages
                page = request.GET.get("page", 1)
                rooms = paginator.page(page)
                return render(
                    request,
                    "rooms/search.html",
                    {
                        "form": form,
                        "rooms": rooms,
                        "page": page,
                        "num_pages": num_pages,
                    },
                )

        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html", {"form": form,},)


class EditRoomView(user_mixins.LogInRequiredView, UpdateView):
    model = models.Room
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "adress",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )
    template_name = "rooms/room_edit.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host != self.request.user:
            raise Http404()
        return room


class RoomPhotosView(user_mixins.LogInRequiredView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if user != room.host:
            messages.error(request, "Can't Delete that Photo")
        else:
            room.photos.filter(pk=photo_pk).delete()
            messages.success(request, "Deleted Photo")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LogInRequiredView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    pk_url_kwarg = "photo_pk"
    template_name = "rooms/photo_edit.html"
    fields = ("caption",)
    success_message = "Photo Update"

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(user_mixins.LogInRequiredView, SuccessMessageMixin, FormView):
    model = models.Photo
    template_name = "rooms/photo_add.html"
    fields = ("caption", "file")
    form_class = forms.AddPhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        messages.success(self.request, "Uploaded Photo")
        form.save(pk)
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LogInRequiredView, SuccessMessageMixin, FormView):

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, "Created Room")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/detail.html
{% extends "base.html" %}

{% block page_name %}
    Home
{% endblock page_name %}

{% block content %}
<div>
    <h1>{{room.name}}</h1>
    <p>{{room.description}}</p>
</div>
<div>
    <h3> By : {{room.host.username}}
    {% if room.host.superuser %}
        (superhost)
    {% endif %}
    </h3>
</div>
<div>
    <h3>Amenities</h3>
    <ul>
    {% for item in room.amenities.all %}
        <li>{{item}}</li>
    {% endfor %}
    </ul>
    <h3>Facilities</h3>
    <ul>
    {% for item in room.facilities.all %}
        <li>{{item}}</li>
    {% endfor %}
    </ul>
    <h3>House Rules</h3>
    <ul>
    {% for item in room.house_rules.all %}
        <li>{{item}}</li>
    {% endfor %}
    </ul>
</div>
{% endblock content %}

templates/rooms/photo_add.html
{% extends "base.html" %}
{% block page_title %}
    Add Photo
{% endblock page_title %}
{% block search_bar %}
{% endblock search_bar %}

{% block content %}
  
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include "mixins/room/room_form.html" with form=form cta="Upload Photo" %}
    </div>
    
    
 
{% endblock content %}

templates/rooms/photo_edit.html
{% extends "base.html" %}
{% block page_title %}
    Photo Edit
{% endblock page_title %}
{% block search_bar %}
{% endblock search_bar %}

{% block content %}
  
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include "mixins/room/room_form.html" with form=form cta="Edit Photo" %}
    </div>
    
    
 
{% endblock content %}

templates/rooms/room_create.html
{% extends "base.html" %}
{% block page_title %}
    Create Room
{% endblock page_title %}
{% block search_bar %}
{% endblock search_bar %}

{% block content %}
  <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-600">
    {% include "mixins/room/room_form.html" with form=form cta="Create" %}
    
  </div>
 
{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{room.name}}
{% endblock page_title %}

{% block content %}
    <div class="-mt-5 contaner max-w-full flex h-75vh mb-20">
        <div class="h-full w-1/2 bg-cover" style="background-image: url({{room.first_photo}});"></div>
        <div class="w-1/2 flex flex-wrap">
            {% for photo in room.get_next_four_photos %}
                <div class="w-1/2 h-auto bg-cover border border-gray-400" style="background-image: url({{photo.file.url}});"></div>
            {% endfor%}
        </div>
    </div>
    <div class="container max-w-full mx-auto flex pb-56 justify-around">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div>
                    <h4 class="text-2xl mb-px font-medium">{{room.name}}</h4>
                    <span>{{room.city}}</span>
                </div>
                <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center ">
                    {% include "mixins/user_avatar.html" with user=room.host %}                    
                    <span class="mt-1 ">
                        {{room.host.first_name}}
                    </span>
                </a>
            </div>
            <div class="flex border-section">
                <span class="mr-5 font-light">{{room.room_type}}</span>
                <span class="mr-5 font-light">{{room.beds}} bed{{room.beds|pluralize}}</span>
                <span class="mr-5 font-light">{{room.guests}} guest{{room.guests|pluralize}}</span>
                <span class="mr-5 font-light">{{room.baths}} bath{{room.baths|pluralize}}</span>
                <span class="mr-5 font-light">{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</span>
            </div>
            <p class="border-section">
                {{room.description}}
            </p>
            <div class="border-section">
                <h4 class="text-lg font-medium mb-5">Amenities</h4>
                {% for a in room.amenities.all %}
                    <li>{{a}}</li>
                {%endfor%}
            </div>
            <div class="border-section">
                <h4 class="text-lg font-medium mb-5">Facilities</h4>
                {% for a in room.facilities.all %}
                    <li>{{a}}</li>
                {%endfor%}
            </div>
            <div class="border-section">
                <h4 class="text-lg font-medium mb-5">House Rules</h4>
                {% for a in room.house_rules.all %}
                    <li>{{a}}</li>
                {%endfor%}
            </div>
            <div >
                <h4 class="text-2xl font-medium mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div >
                        <i class="fas fa-star text-teal-500"></i>
                        <span class="font-bold text-xl">{{room.total_rating}}</span>
                    </div>
                    <div class="h-5 w-px bg-gray-700 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl">{{room.reviews.count}}</span>   
                        <span>review{{room.reviews.count|pluralize}}</span>   
                    </div>
                </div>
                <div class="mt-10">
                    {% for review in room.reviews.all %}
                        <div class="border-section">
                            <div class="mb-3">
                                <div class="">
                                    {% include "mixins/user_avatar.html" with user=review.user h_and_w='h-10 w20' text='text-xl'%}
                                </div>
                                <div class="flex flex-col">
                                    <span class="font-medium">{{review.user.first_name}}</span>
                                    <span class="text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
                                </div>
                                        
                            </div>
                            <p>
                                {{review.review}}
                            </p>
                        </div>   
                    {% endfor%}
                </div>
            </div>
        </div>
        <div class="w-1/3">
            {% if user == room.host %}
                <a href="{% url "rooms:edit" room.pk %}" class="btn-link block">Edit Profile</a>
            {% else %}
                {% if not request.session.is_hosting %}
                    {% for calendar in room.get_calendars %}
                        <div class="mb-20">
                            <span class="block mb-5">
                                {{calendar.get_month}} / {{calendar.year}}
                            </span>
                            <div class="cal-grid text-center">
                                {% for day in calendar.day_names %}
                                    <span>{{day}}</span>
                                {% endfor %}
                            </div>
                            <div class="cal-grid ">
                                {% for day in  calendar.get_days %}
                                    {% if day != 0 %}
                                        <span class="hover:bg-teal-500 text-center cursor-pointer">{{day}}</span>
                                    {% else %}
                                        <span></span>    
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        
                    {% endfor %}
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/rooms/room_edit.html
{% extends "base.html" %}
{% block page_title %}
    Update
{% endblock page_title %}
{% block search_bar %}
{% endblock search_bar %}

{% block content %}
  <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-600">
    {% include "mixins/room/room_form.html" with form=form cta="Update" %}
    
    
      <div class="mt-3">
        <span><a href="{% url 'rooms:photos' room.pk %}" class="text-teal-500 font-semibold">Edit Photos</a>
    </div>
  </div>
 
{% endblock content %}

templates/rooms/room_list.html
{% extends "base.html" %}

{% block page_title %}
Home
{% endblock page_title %}
{% block content %}
<div class="container mx-auto">
  <div class="rounded-xl mx-auto bg-gray-800 h-25vh mt-32 mb-24 bg-cover bg-center" style="background-image:url(https://images.unsplash.com/photo-1536315238512-4c8cebdaaf93?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop)">
  </div>
  <div class="flex flex-wrap">
    {% for room in rooms %}
      {% include "mixins/room_card.html" with room=room%}
    {% endfor %}
  </div>
  <div class="container flex items-center justify-center mx-auto">
    {% if page_obj.has_previous %}
      <a href="?page={{page_obj.previous_page_number}}"><i class="fas fa-arrow-left text-teal-400"></i></a>
    {% endif %}
      <span class="mx-3">
        {{page_obj.number}} of {{page_obj.paginator.num_pages}}
      </span>
    {% if page_obj.has_next %}
      <a href="?page={{page_obj.next_page_number}}"><i class="fas fa-arrow-right text-teal-400"></i></a>
    {% endif %}
  </div>
</div>

{% endblock content %}

templates/rooms/room_photos.html
{% extends "base.html" %}
{% block page_title %}
    {{room.name}}'s Photos
{% endblock page_title %}
{% block search_bar %}
{% endblock search_bar %}

{% block content %}
    <div class="container mx-auto my-10">
        <div class="w-full mb-5">
            <a href="{% url 'rooms:add-photo' room.pk %}" class="w-1/5 btn-link block"> Upload Photo </a>
        </div>
        {% for photo in room.photos.all %}
            <div class="flex items-center justify-between mb-5 p-6 border border-gray-500">
                <div class="flex items-start">
                    <img src={{photo.file.url}} class="w-32 h-32 "/>
                    <span class="ml-5"> {{photo.caption}}</span>
                </div>
                <div class="flex flex-col w-1/5 ml-5">
                    <a href="{% url "rooms:edit-photo" room.pk photo.pk %}" class="btn-link mb-5 bg-teal-500">Edit</a>
                    <a href="{% url "rooms:delete-photo" room.pk photo.pk %}" class="btn-link">Delete</a>
                </div>
            </div>
        {% endfor %}
        <div class="flex justify-center mt-10">
            <a href="{% url "rooms:edit" room.pk %}" class="text-lg text-teal-500 ">Back to Edit</a>
        </div>
    
    </div>
   
 
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}
{% block page_title %}
    Search
{% endblock page_title %}
{% block search_bar %}
  <form method="get" action="{% url "rooms:search" %}">
    {{form.as_p}}
    <button>Search</button>
  </form>
  <h4>Result</h4>
  {% for room in  rooms %}
    <h3>{{room.name}}</h3>
  {% endfor %}
  {% if rooms.has_previous %}
    <a href="?page={{rooms.previous_page_number}}">previous</a>
  {% endif %}
  {{page}}/{{num_pages}}
  {% if rooms.has_next %}
    <a href="?page={{rooms.next_page_number}}">next</a>
  {% endif %}
{% endblock search_bar %}

{% block content %}
 <h4> Search </h4>
  <h4> Search by </h4>
  

{% endblock content %}